pipeline
{
	agent any
	stages 
	{
		stage('Builder') 
		{
			environment
			{
				SAUCE_ACCESS = credentials('mydtr_cre')
				IMAGE_NAME = 'dcdevjbz/msbuild15:ver15.4.8.50001_wincore1709'
				WPFBUILDER_NAME = 'dcdevjbz/wpfsdk_builder:ver15.4.8.50001_wincore1709'
			}
			steps 
			{
				script
				{
					powershell 'if(( docker images -q ${env:IMAGE_NAME}) -eq $null ) { docker build -f ${PWD}\\constructor\\basicbuilder\\Dockerfile -t ${env:IMAGE_NAME} ${PWD}\\constructor\\basicbuilder; ${env:SAUCE_ACCESS_PSW} | docker login --username ${env:SAUCE_ACCESS_USR} --password-stdin; docker push ${env:IMAGE_NAME} } else {Write-Output "found ${env:IMAGE_NAME}"}'
				}

				script
				{
					powershell 'if ( (docker images -q ${env:WPFBUILDER_NAME}) -eq $null ) `
					{ docker build -f ${PWD}\\constructor\\wpfsdkbuilder\\Dockerfile -t ${env:WPFBUILDER_NAME} ${PWD}\\constructor\\wpfsdkbuilder } `
					else {Write-Output "found ${env:WPFBUILDER_NAME}"}'
				}
			}
		}
	}
}