pipeline
{
	agent any
	stages 
	{
		stage('build source') 
		{
			environment
			{
				USERNAME = credentials('dtr_id')
				PASSWORD = credentials('dtr_password')
				IMAGE_NAME = 'net4xbuilder'
				COMMITHASH = ''
			}
			steps 
			{
				script
				{
					def output = powershell(returnStdout: true, script: '$env:COMMITHASH=(git -C ${PWD} log -1 --format="%h")')
					println(output)					
					powershell 'Write-Output ${env:COMMITHASH}'
					powershell '''if(( docker images -q ${env:IMAGE_NAME}) -ne $null ) 
							{$commithash=(git -C ${PWD} log -1 --format="%h"); 
							($machinename="mynet4builder"+$commithash);
							docker run --rm -d --name=$machinename --env myusername=$env:USERNAME --env mypassword=$env:PASSWORD -t ${env:IMAGE_NAME};
							docker exec $machinename cmd /k 'set'
							docker stop $machinename}'''
				}
			}
		}
	}
}