pipeline
{
	agent any
	stages 
	{
		stage('build source') 
		{
			environment
			{
				USERNAME = credentials('dtr_id')
				PASSWORD = credentials('dtr_password')
				IMAGE_NAME = 'net4xbuilder'
			}
			steps 
			{
				script
				{
					def commit_hash = powershell(returnStdout: true, script: 'git -C ${PWD} log -1 --format="%h"')
					powershell """Write-Output ${commit_hash}"""
					powershell """Write-Output ${IMAGE_NAME}"""
					powershell """ PWD """
					
					powershell """if(( docker images -q ${IMAGE_NAME} ) -ne "" ) 
							{($machinename="mynet4builder_${commit_hash}");
							docker run --rm -d --name=${machinename} --env myusername=${USERNAME} --env mypassword=${PASSWORD} -t ${IMAGE_NAME};
							docker exec ${machinename} cmd /k 'set'
							docker stop ${machinename}} """
				}
			}
		}
	}
}