pipeline
{
	agent any
	stages 
	{
		stage('build source') 
		{
			environment
			{
				USERNAME = credentials('dtr_id')
				PASSWORD = credentials('dtr_password')
				IMAGE_NAME = 'net4xbuilder'
			}
			steps 
			{
				script
				{
					
					powershell '$githash=git -C ${PWD} log -1 --format="%h"'
					powershell 'Write-Output "commit hash: $githash" '
					powershell '''if(( docker images -q ${env:IMAGE_NAME}) -ne $null ) 
							{$commithash=(git -C ${PWD} log -1 --format="%h"); 
							($machinename="mynet4builder"+$commithash);
							docker run --rm -d --name=$machinename --env myusername=$env:USERNAME --env mypassword=$env:PASSWORD -t ${env:IMAGE_NAME};
							docker exec $machinename cmd /k 'set'
							docker stop $machinename}'''
				}
			}
		}
	}
}